ARG base=
FROM ${base}

RUN sed -i '/\(jessie\|wheezy\)-updates/ d; \
            /wheezy/ s://deb\.debian\.org://archive\.debian\.org:g' /etc/apt/sources.list && \
    apt-get update && \
    apt-get install -y sudo openssl gcc && \
    apt-get clean && \
    useradd --create-home --user-group --password $(openssl passwd -1 a) user && \
    echo 'user ALL=(ALL) ALL' >> /etc/sudoers

WORKDIR /home/user
USER user:user
COPY --chown=user:user install_mkl.sh .
ENTRYPOINT ["/bin/bash", "-c"]
